import { Network } from '../types';
export declare const DENOMINATOR = 10000;
export declare const RECALCULATION_TX_TIME = 1000;
export declare const RECALCULATION_TIME = 2000;
export declare const LOADING_ANIMATION_TIME = 3000;
export declare const ANIMATION_PAUSE_TIME = 3000;
export declare const MODULES_ACCOUNT: string;
export declare const MODULES_V05_ACCOUNT: string;
export declare const RESOURCES_ACCOUNT: string;
export declare const RESOURCES_V05_ACCOUNT: string;
export declare const COINS_ACCOUNT: string;
export declare const COIN_INFO = "0x1::coin::CoinInfo";
export declare const COIN_STORE = "0x1::coin::CoinStore";
export declare const CURVE_UNCORRELATED: string;
export declare const CURVE_UNCORRELATED_V05: string;
export declare const CURVE_STABLE: string;
export declare const CURVE_STABLE_V05: string;
export declare const RECALCULATION_BALANCE_TIME = 7000;
export declare const NETWORKS_MODULES: {
    Scripts: string;
    Faucet: string;
    LiquidityPool: string;
    CoinInfo: string;
    CoinStore: string;
};
export declare const SHORT_LIQUIDSWAP_DEMO_TAG = "devops.mom";
export declare const LIQUIDSWAP_API_URL: any;
export declare const MAINNET_CHAIN_ID = 1;
export declare const APTOS_TESTNET_CHAIN_ID = 2;
export declare const PONTEM_TESTNET_CHAIN_ID = 4;
export declare const APTOS = "0x1::aptos_coin::AptosCoin";
export declare const DOODOO = "0x73eb84966be67e4697fc5ae75173ca6c35089e802650f75422ab49a8729704ec::coin::DooDoo";
export declare const NETWORKS: Network[];
export declare const CORRECT_CHAIN: string;
export declare const CORRECT_CHAIN_ID: number;
export declare const VERSION_0 = 0;
export declare const VERSION_0_5 = 0.5;
export declare const VALID_VERSIONS: number[];
export declare const WALLET_GOOGLE_PLAY_URL = "https://play.google.com/store/apps/details?id=com.pontemmobilewallet&hl=en&gl=US";
export declare const WALLET_CHROME_STORE_URL = "https://chrome.google.com/webstore/detail/pontem-aptos-wallet/phkbamefinggmakgklpkljjmgibohnba";
export declare const PONTEM_API_URL = "https://control.pontem.network/api";
export declare const API_KEY: any;
